ok we should be good now

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -64,8 +64,17 @@ jobs:
           command: |
             set +e
             docker-compose run --name apitest odt-api-tests
+            BOMBED=$?
             docker cp apitest:/app/output/apiresults.xml ~/app/output/xunit
             docker-compose down
+            if [ -z "$BOMBED" ];
+            then
+                echo "no errors"
+                exit 0
+            else
+                echo "errors"
+                exit 1
+            fi;
 
       - run:
           name: Testing Jobs
@@ -73,8 +82,17 @@ jobs:
           command: |
             set +e
             docker-compose run --name jobtest odt-jobs-tests
+            BOMBED=$?
             docker cp jobtest:/app/output/jobresults.xml ~/app/output/xunit
             docker-compose down
+            if [ -z "$BOMBED" ];
+            then
+                echo "no errors"
+                exit 0
+            else
+                echo "errors"
+                exit 1
+            fi;
       
       - store_artifacts:
           path: ~/app/output
